// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Scene00 = 0,
	Scene01 = 1,
	Scene02 = 2,
	Scene03 = 3,
	Scene04 = 4,
	Scene05 = 5,
	Scene06 = 6,
	Scene07 = 7,
	Scene08 = 8,
	Scene09 = 9,
	Scene10 = 10,
	Scene11 = 11,
}
